### ISSUE TITLE
Bug: Test keydown event on contenteditable element 

### ISSUE THREAD

**Issue by leopsidom** [vuejs/test-utils#1335] opened 2022-02-20 20:47 UTC
**Describe the bug**
Not able to test keydown event on a contenteditable element. When triggering a keydown event with { key: ... }, the wrapper on the component doesn't contain text with the key.

**To Reproduce**
I created a simple test case here: https://stackblitz.com/edit/vitejs-vite-uetfze?file=test/DivContentEditable.test.ts. To see the failure, just run `vitest`.

Current error: `expected '' to include 'a'`.

**Expected behavior**
The test should pass.

**Related information:**
- `@vue/test-utils` version:  "*"
- `Vue` version: 3.2.25
- `node` version: 14.17.0
- `npm` (or `yarn`) version: 7.17.0

**Additional context**

**Comment by lmiller1990** [comment] 2022-02-21 00:54
I don't think this test is written correctly. You'll likely need to do a deep dive into exactly what happens when a div is `contenteditable`, but I'm sure this is not going to work, even in a browser w/o VTU. In my experience the only way to write to a contentediable programmatically is using `document.execCommand`: [docs](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand).

We specialize in Vue components specifically in this library, and this is just a regular old HTML element, more or less - while your test isn't working, I'm sure this is not a bug in Test Utils, but simply the wrong events getting dispatched on the HTML element, or jsdom not fully implementing contenteditable, or both.

If you really want to test something like this in jsdom with Test Utils, I've done it like this before: https://github.com/lmiller1990/vuejs-composition-api-course/blob/main/tests/unit/PostWriter.spec.ts (see `PostWriter` for implementation using contenteditable).

For next steps, I'd recommend:

- try using `document.execCommand`
- research what events you need to to use contenteeditable programatically
- try that here

It'll likely be something like this:

```js
const wrapper = mount(Comp, {
  attachTo: document // you need attachTo, or you cannot focus the element most likely
})

await wrapper.find('div').focus()
document.execCommand('insertText', false, 'Some text')
// assert?
```

I am sorry I cannot produce a working example right now, I spent a bit of time but I can't spend any more. Please post if you figure it out. I don't see any VTU specific problem here though, so I will close this one as a bug. Remember, if you want to drop down the to raw HTML (which you will likely need to do) you can use `wrapper.find('div').element`.

**Closed by lmiller1990** 2022-02-21 00:54 UTC
Labels: bug

**Comment by leopsidom** [comment] 2022-02-23 02:19
@lmiller1990 Thanks for the detailed reply. I'm guessing this is jsdom limitation then, due to the fact the event is fired as `isTrusted: false`.  So the event cannot update the value of contenteditable: https://stackoverflow.com/a/44190874/4983450. we might end up leveraging end 2 end testing framework like playwright or selenium for some specific  testing cases while using VTU for unit test specifically. It's kind of unfortunate some cases can't be unit tested. 

There might be some hacky way to make it work though as in this SO answer: https://stackoverflow.com/a/64991159/4983450. I might try it out at some point just not quite sure about the security implication.

**Comment by lmiller1990** [comment] 2022-02-24 00:44
I'm kind of curious about what the actual limitation is here. If it's truly a jsdom limitation, you could still run Test Utils in a browser (you would need Mocha or something to run the tests) or you could use Cypress (my preference, I work on it full time) or one of the others. If you are interested, Cypress has pretty good Component Testing support (using Test Utils under the hood).  See https://www.cypress.io/blog/2021/04/06/getting-start-with-cypress-component-testing-vue-2-3/. I also recorded some content about Test Utils + Cypress, if you are interested: https://www.youtube.com/watch?v=qZKEbfHY_t0.

If you go down the Cypress route, happy to help out - I don't have much experience w/ Playwright though, and I don't want to go back to Selenium.
