### ISSUE TITLE
Bug: TypeError: $setup.mergeProps is not a function

### ISSUE THREAD

**Issue by ricardovanlaarhoven** [vuejs/test-utils#2365] opened 2024-03-11 07:46 UTC
Original:  https://github.com/vuejs/vue-test-utils/issues/2091

### Subject of the issue

When using vue's mergeprops in a component that's being tested, i'm getting an error

### Steps to reproduce
Mount a component that is using `import { mergeProps } from "vue";`

### Expected behaviour

A working mount

### Actual behaviour

`TypeError: $setup.mergeProps is not a function`

**Comment by cexbrayat** [comment] 2024-03-11 07:56
Hi @ricardovanlaarhoven 

Can you provide us a small repro online using https://stackblitz.com/github/vuejs/create-vue-templates/tree/main/typescript-vitest?file=src%2Fcomponents%2F__tests__%2FHelloWorld.spec.ts ? 

It only takes a few minutes, and we'll be able to take a look

**Comment by ricardovanlaarhoven** [comment] 2024-03-11 11:30
I hsould have made a reproduction before. Then i knew what the issue was.
I use a composable, and that composable depends on an inject. When there is nothing provided, it throws an error since the developer then made a mistake.

In my test i forgot to provide something, so the throw is called, and then for some reason this error pops up. Which is strange, so i like someone to take a look at it. Perhaps a better error can be thrown. The error that i throw.

Here is my reproduction.

Run the tests, and see there is a weird error. When you remove line 5 from the composables/useSomething.ts `  if(!form) throw "No form to inject"` The error is gone.

**Comment by cexbrayat** [comment] 2024-03-11 13:02
@ricardovanlaarhoven You forgot the link to the repro 😉

**Comment by ricardovanlaarhoven** [comment] 2024-03-14 07:40
Lol.. must be a monday..

https://stackblitz.com/edit/github-wnubin

**Comment by cexbrayat** [comment] 2024-03-14 08:57
Thanks 👍

I think this is a duplicate of #2319 : the thrown error is hidden and $setup gets all its properties undefined.

**Closed by cexbrayat** 2024-03-14 08:57 UTC
Labels: bug, needs reproduction
