### ISSUE TITLE
Feature request: Testing Vue3 computed properties with TypeScript SFC

### ISSUE THREAD

**Issue by felixzapata** [vuejs/test-utils#1791] opened 2022-10-04 08:11 UTC
Hi, I came across [this link from stackoverflow](https://stackoverflow.com/questions/71442106/testing-vue3-computed-properties-with-typescript-sfc), searching from time to time on how to access the properties created, using the _vm_ object.

Sometimes I find an alternative to avoid this problem, but other times I am a little stuck, and using the _defineExpose_ just for testing purposes is a little weird, besides the solution described on the link about typing the wrapper I don't know if it is the best solution for all the cases.

**Comment by cexbrayat** [comment] 2022-10-04 08:20
You can access everything on the vm object, even if it is not exposed, as we enable this in VTU.

The issue is that TS will complain about it, but you can simply cast the VM object to remove the error.

See https://github.com/vuejs/test-utils/blob/60ff6bd993155f632e6ddbbd93af3d1e7dd4b6b2/tests/expose.spec.ts 

There is sadly nothing we can do in VTU for now, as we're waiting for changes in Vue itself to get the proper types.

You can subscribe to #972 to follow the progress.
Closing this one as duplicate

**Closed by cexbrayat** 2022-10-04 08:20 UTC
