### ISSUE TITLE
setData() on a writable computed property does not seem to work as it does in VTU.1

### ISSUE THREAD

**Issue by nsakiya-incomm** [vuejs/test-utils#2259] opened 2023-11-25 18:28 UTC
I'm trying to test a little logic inside the setter of a computed property by calling "wrapper.setData({ selectedValue: ["Work","Home"] }). It ran fine in VTU v.1, but it doesn't seem to call the setter at all in v.2. I'm wondering if this feature is still being supported as I don't see the computed property is mentioned in v.2 documentation at all. Or, am I missing something here.

`  computed: {                                                                                                           `
`    selectedValue: {                                                                                                    `
`      get() {                                                                                                           `
`        if (!this.multiple && this.$store.getters.selectedLocation!=null) {                                             `
`          return this.$store.getters.selectedLocation[0]                                                                `
`        } else {                                                                                                        `
`          return this.$store.getters.selectedLocation;                                                                  `
`        }                                                                                                               `
`      },                                                                                                                `
`      set(value) {                                                                                                      `
`        if (this.multiple && value && value.length > 1 && value.length > this.$store.getters.selectedLocation.length) { `
`          let sortedSelectedItems = value.sort((a,b) => {                                                               `
`            if (a === "All Locations") {                                                                                `
`              return -1;                                                                                                `
`            } else if (b === "All Locations") {                                                                         `
`              return 1;                                                                                                 `
`            } else {                                                                                                    `
`              return a.toLowerCase().localeCompare(b.toLowerCase())                                                     `
`            }                                                                                                           `
`          })                                                                                                            `
`          value = sortedSelectedItems;                                                                                  `
`        }                                                                                                               `
`                                                                                                                        `
`        if (!this.multiple && value!=null) {                                                                            `
`          value = [value];                                                                                              `
`        }                                                                                                               `
`        this.$store.commit("setSelectedLocation", value);                                                               `
`      }                                                                                                                 `
`    },                                                                                                                  `
`	...                                                                                                                  `
`  },                                                                                                                    `

Here's the test.
`    wrapper = mount(Component, {                                    `
`      attachTo: "#root",                                            `
`      global: {                                                     `
`        mocks: {                                                    `
`          $http: axios                                              `
`        },                                                          `
`        plugins: [store, vuetify]                                   `
`      }                                                             `
`    });                                                             `
`    wrapper.setData({ selectedValue: ["Work","Home"] });            `
`    expect(wrapper.vm.selectedValue).toMatchObject(["Home","Work"]);`

**To Reproduce**
Having a component with writable computed property with a test that updates the property as shown above.
https://stackblitz.com/edit/github-dbkkwg?file=src%2Fcomponents%2F__tests__%2FHelloWorld.spec.ts

**Expected behavior**
After running the test, the selectedValue doesn't get updated, and still hold the default value.

**Related information:**
`  System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1265U
    Memory: 6.69 GB / 15.54 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  npmPackages:
    @vue/test-utils: ^2.0.0-0 => 2.4.2 
    jest: ^29.7.0 => 29.7.0 
    vue: ^3.2.26 => 3.3.8 `

**Additional context**

**Comment by cexbrayat** [comment] 2023-11-25 18:50
Hi @nsakiya-incomm 

Can you provide us a small repro online (as minimal as possible to reproduce the issue, ideally without vuteify, the store and axios) using https://stackblitz.com/github/vuejs/create-vue-templates/tree/main/typescript-vitest?file=src%2Fcomponents%2F__tests__%2FHelloWorld.spec.ts ? 

It only takes a few minutes, and we'll be able to take a look

**Comment by nsakiya-incomm** [comment] 2023-11-27 09:03
Thanks, @cexbrayat .
Here is the sample codes, based on your template. I'm new to stackblitz.
https://stackblitz.com/edit/github-dbkkwg?file=src%2Fcomponents%2F__tests__%2FHelloWorld.spec.ts

**Comment by nsakiya-incomm** [comment] 2023-11-27 21:05
HI @cexbrayat ,
I'm new to this PR process. So, I open a PR and fix the issue by myself? I haven't thought about that.  Can you guide me where to find setData() implementation in the source codes. I can give it a shot w/o knowing what I'm getting into. :)
Thanks

**Comment by cexbrayat** [comment] 2023-11-28 07:24
@nsakiya-incomm You can start by adding a minimal unit test to reproduce the issue here https://github.com/vuejs/test-utils/blob/main/tests/setData.spec.ts

then `setData` is defined in https://github.com/vuejs/test-utils/blob/main/src/vueWrapper.ts#L242, and you'll need to check what's going on 👍 Thanks for your help!

**Comment by renatodeleao** [comment] 2024-03-27 13:23
@nsakiya-incomm Way late to the party, but also had my share of `setData` when doing a big migration so I was compled to leave this comment. 
What was suggested is the way to go, you should test the way user use your components. So whenever you see a `wrapper.vm` around your spider sense should warn you: these are implementation details. The name of data/computed properties are implementation details that can be changed without changing the output.

Now back to the subject:

> cannot directly invoke setValue(). There might be the way, but not without going into their implementation level,

 `.setValue` has a second argument `prop` that allows use to basically `v-model` on components. So on your case all you need to do is:

```js
    const inputComponent = wrapper.findComponent({ name: 'HelloWorldChild' });
    await inputComponent.setValue('Overridden!!!', 'modelValue'); // the trick
``` 
Since it's a `vuetify` wrapper, you can even stub it to hide its internal details, but not strictly necessary. Here's a demo with the test passing.
    
https://stackblitz.com/edit/github-dbkkwg-vdtfvm?file=src%2Fcomponents%2F__tests__%2FHelloWorld.spec.ts

Cheers, hope you've made it!

**Comment by cexbrayat** [comment] 2024-03-27 13:34
Oh that's interesting, thanks for the trick @renatodeleao ! 👍

I'll close the issue then, as I think that the two possible workarounds are good enough. 
If someone wants to dig into setData and open a PR, they are more than welcome to of course!

**Closed by cexbrayat** 2024-03-27 13:34 UTC
Labels: bug
