### ISSUE TITLE
Bug: Mocking not working when setup() is defined

### ISSUE THREAD

**Issue by Roywcm** [vuejs/test-utils#1869] opened 2022-11-16 13:36 UTC
**Describe the bug**
I'm trying to mock the vuei18n $t. But this is not working when using the setup composition api. 
When disabling the setup, it works as expected. I also tried with other function names like $test. 
Strange thing is, when using a name without the dollar sign, it also works just normal. 

**To Reproduce**

index.vue
```
<template>
    <div> {{ $t('hello') }}</div>
</template>
<script>
  export default {
    setup(){
        return {} // will not work
    },
  }
</script>
```

test file
```
import { config, mount } from '@vue/test-utils'
import Index from './index'

config.global = {
    mocks: {
        $t: (msg) => msg
    }
}

describe ('Index Tests', () => {
     it ('should mount without crashing', () => {
         const wrapper = mount(Index)
         expect(wrapper).toBeTruthy();
     })
});

````

**Expected behavior**
Should also works when using the composition api.

**Related information:**
- `@vue/test-utils` version: 2.2.3
- `Vue` version: 3.2.45
- `node` version: v18.2.0
- `npm` (or `yarn`) version: 8.10.0

**Comment by simonvizzini** [comment] 2022-11-16 15:22
Oh that interesting, because we are still using Vue v3.2.41 and this issue appeared after updating test-utils to v2.2.3. I just did a downgrade to v2.2.1 and the error is now gone.

**Comment by cexbrayat** [comment] 2022-11-16 20:02
I _may_ have found a way to make this use-case work with Vue v3.2.45
Once #1871 is merged and released, you should be able to upgrade to the latest version of Vue and VTU

**Closed** 2022-11-20 22:32 UTC
Labels: bug

**Comment by JeremCafeyn** [comment] 2022-11-21 07:53
Hey @cexbrayat,
Thanks for the fix! It helps a lot.
In order to not add the global mocks in each .spec files, I tried to add it in the setup file of vitest but it doesn't work.
Do you know if it's related to Vitest?
Here is my code:

```
import matchers from '@testing-library/jest-dom/matchers';
import { config, RouterLinkStub } from '@vue/test-utils';
import { expect, vi } from 'vitest';

config.global.mocks = {
  $t: (key: string) => key, // just return translation key
};
expect.extend(matchers);

```

**Comment by cexbrayat** [comment] 2022-11-21 08:15
@JeremCafeyn Happy to hear that 👍

For global mocks, can you provide us a small repro online using https://stackblitz.com/edit/vitest-dev-vitest-qoiwy3?file=package.json&initialPath=__vitest__ ? I'll take a look to check if this is a VTU issue.

**Comment by stefanlivens** [comment] 2022-11-22 15:39
we still have the same error. downgrading to 2.2.2 fixes it immediately... using a combination of options api and composition api in our project. and since 2.2.3 we get this problem: global mocks just disappear (in our case, we 'enhanced' the mount/shallowMount with mocks for all vue-i18n methods, so all our mount/shallowMount have this mocked vue-i18n methods, even adding a mocked $router just ... disappears...)
But we're using vue 3.2.45 in both cases!
If i try vue3.2.41 and vtu 2.2.4 i get the errors too.

**Comment by cexbrayat** [comment] 2022-11-22 16:18
@stefanlivens Can you provide us a small repro online using https://stackblitz.com/edit/vitest-dev-vitest-qoiwy3?file=package.json&initialPath=__vitest__ ?

**Comment by JeremCafeyn** [comment] 2022-11-23 08:01
> @JeremCafeyn Happy to hear that 👍
> 
> For global mocks, can you provide us a small repro online using https://stackblitz.com/edit/vitest-dev-vitest-qoiwy3?file=package.json&initialPath=__vitest__ ? I'll take a look to check if this is a VTU issue.

Sure! and thanks for your reply. Here you go:
https://stackblitz.com/edit/vitest-dev-vitest-f3omsf?file=components/AsAsync.vue

I included a setup file in the test folder to change the global config, and change also the vitest.config.
I added a $t in the AsAsync component and now it failed.

**Comment by cexbrayat** [comment] 2022-11-23 08:06
@JeremCafeyn If you use `"@vue/test-utils": "2.2.4",` in package.json, then the tests succeed (Stackblitz uses v2.2.3 in your example I think)

**Comment by stefpb** [comment] 2022-12-07 15:14
Remove the `$` in all global properties names and mocks helps us in this situation.

**Comment by renatodeleao** [comment] 2022-12-31 11:57
Have the exact same scenario as https://github.com/vuejs/test-utils/issues/1869#issuecomment-1323871215, have mixed options API component with a `setup()` function. In these mixed components  $ prefixed mocks are ignored (including $route/$router), renaming them without `$` makes them work 🤯 

Cannot reproduce with a bare [vitest stackblitz](https://stackblitz.com/edit/vitejs-vite-idreug?file=test/App.spec.js), so must be something on my dev environment?! :/  @stefanlivens appreciate if you have more info on it

Cheers 👋 

Stack
```
jest@29.3.1"
@vue/vue3-jest@29.2.2
@vue/test-utils@2.2.6
@vue@3.2.45
@vue/compat@3.2.45
```

**Comment by cexbrayat** [comment] 2023-01-03 13:13
Hmm that's strange. I'm not surprised that having a component with both composition and options API has a weird behavior, as the VTU codebase now distinguishes the 2 cases. More than that, I'm surprised that this can only be reproduced with Jest. If we don't have a way to reproduce this in the VTU test suite, this is going to be hard even to just take a look.

Ideally, you should try to move to a component with only a setup or a component with plain Option API. Trying to fix this "mix component case" in VTU is going to add even more complexity to something that is already quite tricky I'm afraid.

**Comment by renatodeleao** [comment] 2023-01-03 17:59
> Ideally, you should try to move to a component with only a setup or a component with plain Option API. 

At the scale of the app I'm working that's not doable ATM. Also `setup()` is a perfectly valid component option for Options API at the time of writing, so I don't think I have a strong argument to present to my team for enforcing that style. Unless vue docs explicitly mention _"do not use `setup()` with other options besides props/name/inheritAttrs.."_ I can't go down that path.

> Trying to fix this "mix component case" in VTU is going to add even more complexity to something that is already quite tricky I'm afraid.

With that, I fully agree. You're already relying on `devtoolsRawSetupState` internal property to make the `2.2.3` patch and from my limited understanding of vue core codebase and investigation, the only way to make this work would be to rely on another internal prop [`__isScriptSetup`](https://github.com/vuejs/core/blob/f73925d76a76ee259749b8b48cb68895f539a00f/packages/runtime-core/src/componentPublicInstance.ts#L401). Not seeing any other way.



**Another weird part**: the reason you add the `if` block in the first place was to avoid a Proxy set error, but _on my end_ patching the VTU@2.2.6 and code and remove the `if (hasSetupState(this))` block altogether makes it work with no warnings or errors for both options API, "mixed" and `<script setup>` components 🤷 

https://github.com/vuejs/test-utils/blob/a48712de2cdc5a97088d836fd4351211e65fde84/src/mount.ts#L481-L485

**Comment by stefanlivens** [comment] 2023-01-04 12:16
hi guys, i simply could _not_ reproduce it in the stackblitz setup. and i missed your call to help, my bad

However, i can confirm v2.2.7 fixed the issue for me!

**Comment by renatodeleao** [comment] 2023-01-04 12:45
Hey @stefanlivens no worries about that! You already helped a lot by demonstrating that I was not the only one with the issue! That's what drove me to find a solution, otherwise, I would just give up and accept as a fact that the problem was with my setup!

**Comment by pavholm** [comment] 2025-05-23 14:20
hi! seems like it's broken again in 2.4.6.
when i'm trying to get `wrapper.vm.$analytics`, now it references to actual implementation and not on the mock. of course, it crashes tests, because when i'm trying to check calls via `toHaveBeenCalled`, it returns `Matcher error: received value must be a mock or spy function`.

can you check it please?

here are screenshots with different versions:
<img width="1178" alt="Image" src="https://github.com/user-attachments/assets/8c61103b-24b3-40d8-b14f-f50d7e1e4408" />

<img width="1114" alt="Image" src="https://github.com/user-attachments/assets/82f1e3b3-f1f2-42f4-a5cd-0354f239fbaa" />
