### ISSUE TITLE
Bug: isDeepRef causes "RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by vladislavkn** [vuejs/test-utils#2394] opened 2024-04-03 08:37 UTC
**Describe the bug**

When objects with circular links are passed as props to a vue component that is being tested, this causes endless recursion in [isDeepRef function added in 2.4.5](https://github.com/vuejs/test-utils/pull/2356/files#diff-39b2554fd18da165b59a6351b1aafff3714e2a80c1435f2de9706355b4d32351R266)

Reported error:
```
RangeError: Maximum call stack size exceeded
 ❯ isDeepRef node_modules/.pnpm/@vue+test-utils@2.4.5/node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:357:26
    355|  * @returns {boolean} Returns true if the value is a DeepRef, false ot…
    356|  */
    357| var isDeepRef = function (r) {
       |                          ^
    358|     return Vue.isRef(r) || (isObject(r) && Object.values(r).some(isDee…
    359| };
 ❯ isDeepRef node_modules/.pnpm/@vue+test-utils@2.4.5/node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:358:61
 ```

**To Reproduce**

[Minimal reproduction](https://stackblitz.com/edit/github-qhp94u?file=src%2Fcomponents%2F__tests__%2FHelloWorld.spec.ts)
run `npm run test:unit` - HomeView.spec.ts will fail

**Expected behavior**

When isDeepRef function encounters circular link, it returns false.

It can be done with this dirty fix, for example:
```javascript
var isDeepRef = function (r, visited) {
    if (!visited) {
      visited = new Set([r]);
    } else if (visited.has(r)) {
        return false;
    } else {
      visited.add(r);
    }
    return Vue.isRef(r) || (isObject(r) && Object.values(r).some((v) => isDeepRef(v, visited)));
};
```

**Related information:**

```
System:
    OS: macOS 13.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 829.33 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
npmPackages:
    @vue/test-utils: ^2.4.4 => 2.4.5 
    vitest: ^1.3.1 => 1.3.1 
    vue: ^3.4.19 => 3.4.21 
```

**Comment by cexbrayat** [comment] 2024-04-03 08:39
Hi @vladislavkn 

Thanks for the repro, but this is a duplicate of #2370 which is already fixed and will be released soon.

**Closed by cexbrayat** 2024-04-03 08:39 UTC
Labels: bug
