### ISSUE TITLE
Bug: 'Vue is not defined' in every test

### ISSUE THREAD

**Issue by JJBocanegra** [vuejs/test-utils#1573] opened 2022-06-05 12:52 UTC
**Describe the bug**
Updating from `"@vue/test-utils": "2.0.0-rc.21"` to `"@vue/test-utils": "2.0.0"` breaks all tests, stating in everyone the next error:
```
ReferenceError: Vue is not defined
```

The error doesn't point to anywhere in particular or is like broken, because the line it points to is an empty one and if remove the content of the file it still breaks there.

```
ReferenceError: Vue is not defined

      14 |   useStore: () => null,
      15 | }));
    > 16 |
         | ^
      17 | config.global.plugins = [Equal];
      18 |
      19 | config.global.mocks = {
```

**To Reproduce**
I don't know how to reproduce this, only know that it happened after updating this libraries:
```git
-        "jest": "27.5.1",
+        "jest": "28.1.0",
+        "jest-environment-jsdom": "28.1.0",
-        "ts-jest": "27.1.3",
+        "ts-jest": "28.0.4",
```

**Expected behavior**
All tests should pass as they are doing in the version `2.0.0-rc.21`.

**Related information:**
- `@vue/test-utils` version: 2.0.0
- `Vue` version: 3.2.36
- `node` version: 16.14.0
- `npm` (or `yarn`) version: Yarn 1.22.17 and NPM 8.3.1

**Additional context**
My project is using TypeScript.

**Comment by freakzlike** [comment] 2022-06-05 13:35
Duplicate of #1525

Try this solution here https://github.com/vuejs/test-utils/issues/1525#issuecomment-1134620421. Otherwise feel free to reopen this issue.

**Closed by freakzlike** 2022-06-05 13:35 UTC
Labels: bug

**Comment by JJBocanegra** [comment] 2022-06-06 07:41
Sorry, I forgot to remove the `is:open` from the issues filter while searching 😓
