### ISSUE TITLE
The VueWrapper does not update by itself

### ISSUE THREAD

**Issue by KalDev468** [vuejs/test-utils#1106] opened 2021-11-26 16:14 UTC
Hi all

### What we have ?
We have three element:
1. A button
2. A simple html element
3. A component

### Scenario
When we click on the button, the element and the component are removed.

![carbon (3)](https://user-images.githubusercontent.com/95077884/143600022-f55a73f6-16cc-45bf-bd78-24cf83713886.png)

### Tests

**The first test:**

- Check that the element exist in the beginning
- Click on the button
- Check that the element no longuer exist

**The second test:** (Same as the first but for the component)

- Check that the component exist in the beginning
- Click on the button
- Check that the component no longuer exist

![carbon (5)](https://user-images.githubusercontent.com/95077884/143606765-57babad0-260d-420a-a50c-84502ac8c2aa.png)

### Result
The first test works in both versions of VTU.
The second test only works in VTU but fail in VTU-next.

### Problem
For the _**DomWrapper**_ it is necessary to re-search the element to have its new state. this behavior is the same in both versions of VTU, so nothing changed.
But for the **_VueWrapper_**, in VTU, it was not necessary to re-search the component to have its new state, the wrapper updated itself. which is no longer the case in VTU-next. so this is the identified change 

### Debug
Difference between the two versions (after the action of the click, therefore after removing the element|component):

For **DomWrappe**: there is no difference, it is always necessary to redo a search to have the new state of the wrapper.

For **VueWrapper**: without redoing the search
|VTU version/Method|exist()|html()|
|-----------------------|------|-------|
|VTU(Vue 2)|false|HTML code|
|VTU-next(Vue 3)|true|TypeError: Cannot read property '__vue_app__' of null|

### Questions
Is that the new behavior or is it a bug?
If this is the new VueWrapper behavior, do we need to re-search the component after every action or is there a better solution?

### Code
```js
import {mount} from "@vue/test-utils";

const componentA: any = {
    template: `<div>component</div>`
}

const app = {
    template: `
        <div>
            <button @click="isOpen = false">close</button>
            
            <!-- REMOVE AFTER CLICK ON THE BUTTON -->
            <div id="element" v-if="isOpen">element</div>
            <componentA v-if="isOpen"/>
        
        </div>
    `,
    components: {componentA},
    data() {
        return {isOpen: true}
    }
}

test('Element must not exist', async () => {
    let wrapper = mount(app);
    let buttonWrapper = wrapper.find('button');
    let elementWrapper = wrapper.find('#element');

    expect(elementWrapper.exists()).toBeTruthy();

    await buttonWrapper.trigger('click');

    elementWrapper = wrapper.find('#element'); // NECESSARY in both versions of VTU

    expect(elementWrapper.exists()).toBeFalsy();
});

test('Component must not exist', async () => {
    let wrapper = mount(app);
    let buttonWrapper = wrapper.find('button');
    let componentWrapper = wrapper.findComponent(componentA);

    expect(componentWrapper.exists()).toBeTruthy();

    await buttonWrapper.trigger('click');

    // componentWrapper = wrapper.findComponent(componentA);// NECESSARY ONLY IN VUT-NEST

    expect(componentWrapper.exists()).toBeFalsy();
});
```

**Comment by xanf** [comment] 2021-11-26 17:39
I believe this is intended behavior in `vtu-next`. We're expecting you to always get a fresh VueWrapper. Otherwise we will be exposing too much specifics of Vue internals here :)

**Comment by KalDev468** [comment] 2021-11-26 18:51
If this is the desired behavior then it is bad for people like me who have already written tests with the old behavior. it makes the tests fail and in addition it will increases the number of lines of code.

Can you please give me more indication about emulate with proxies ?

**Comment by lmiller1990** [comment] 2021-12-12 04:01
I think we've had this problem before.

- https://github.com/vuejs/vue-test-utils-next/issues/286

Although this was how it worked in VTU v1, I think it was just a co-incidence and not something that was specifically designed. If there is some way to replicate that behavior here, it might be good to do so for backwards compat, but I think that would require access to unexposed Vue internals.

At this point, I don't plan to try and implement this - I'd recommend just re-querying. It's a bit of extra code, but likely makes your tests more reliable by not relying on mutation. 

If you feel strongly about the original behavior, I'd welcome a PR exploring implementing it, but I suspect it will be very complex to do, and potentially break other behaviors. I don't have an intention to implement it in the immediate future, so your options are:

1. Update your tests 
2. Implement this behavior here

**Comment by lmiller1990** [comment] 2023-01-27 06:27
I think we cannot make this change - since Vue is using a vdom anyway, better not to rely on raw DOM references where possible. Instead, re-query to get the latest wrapper.

I'm sorry this was an unintended breaking change, I hope this won't be too disruptive. I don't think it's practical to implement the requested feature here without introducing new bugs or regressions.

**Comment by cexbrayat** [comment] 2023-01-27 08:52
@lmiller1990 Yeah I agree. It does force developers to update a few tests when migrating but I think it's for the best. Let's close this one

**Closed by cexbrayat** 2023-01-27 08:52 UTC
Labels: enhancement
