### ISSUE TITLE
Bug:  module not found

### ISSUE THREAD

**Issue by JuoJuo** [vuejs/test-utils#1269] opened 2022-01-24 12:06 UTC
**Describe the bug**

- Cannot find module 'src/createDomEvent' or its corresponding type declarations.(wrapperLike.d.ts)

**To Reproduce**

- add "@vue/test-utils": "^2.0.0-rc.18" to vite project
- run vue-tsc
- Cannot find module 'src/createDomEvent' or its corresponding type declarations.(wrapperLike.d.ts)

**Expected behavior**

- No error

**Related information:**
- `@vue/test-utils` version: v2.0.0-rc.18
- `Vue` version:  3.2.25
- `node` version: 16
- `npm` (or `yarn`) version: 1.22.4

**Additional context**

![image](https://user-images.githubusercontent.com/36804937/150780056-a53cee88-81ad-407b-a486-988450f657f4.png)

**Comment by JuoJuo** [comment] 2022-01-24 12:11
I want to make a pr, but I can't push my branch

**Comment by cexbrayat** [comment] 2022-01-24 12:26
Hi @JuoJuo  

This is a duplicate of #936, #1206, #1239, and #1268. It was fixed in #1184.

This should be released soon. In the meantime, you can use `skipLibCheck` in your tsconfig.

**Comment by JuoJuo** [comment] 2022-01-24 12:27
thanks

**Closed by cexbrayat** 2022-01-24 12:26 UTC
Labels: bug
