### ISSUE TITLE
Bug: focus active

### ISSUE THREAD

**Issue by hzhoup** [vuejs/test-utils#2176] opened 2023-08-31 13:45 UTC
**Describe the bug**

when i test the focs event, the document.activeElement is the full `body`, like this:
![image](https://github.com/vuejs/test-utils/assets/109516832/95124ba5-df2f-43e9-ade9-9ee38c48fcf0)

**To Reproduce**

https://stackblitz.com/edit/github-3auzsz?file=src%2Fcomponents%2F__tests__%2FHelloWorld.spec.ts,src%2Fcomponents%2FHelloWorld.vue

**Expected behavior**

the `document.activeElement` is `wrapper.element`

**Related information:**

"@vue/test-utils": "^2.4.1"
"jsdom": "^22.1.0"
"vitest": "^0.34.3"

**Additional context**

**Comment by cexbrayat** [comment] 2023-08-31 14:02
Hi @hzhoup 

As you are triggering the focus event on the whole wrapper, that looks normal to me. What are you trying to test?

**Comment by hzhoup** [comment] 2023-09-01 00:26
i want to test the wrapper focus state, in the [MDN Doc](https://developer.mozilla.org/en-US/docs/Web/API/Document/activeElement), i know `The activeElement read-only property of the Document interface returns the Element within the DOM that currently has focus.`. I think when i trigger `focus`, the `document.activeElement` will be return `button` DOM instead of `body`, like try that on the browser.

the preview link: https://stackblitz.com/edit/github-3auzsz-nb39qq?file=src%2Fcomponents%2F__tests__%2FHelloWorld.spec.ts,src%2FApp.vue

the stackblitz side preview is always `iframe`, i open port new tab, in the browser console `document.activeElement` will be show:
![image](https://github.com/vuejs/test-utils/assets/109516832/3288eab8-6a52-4b6b-94d7-775c123b66e3)

**Comment by freakzlike** [comment] 2023-09-02 07:47
Right now, `trigger('focus')` is only dispatching a DOM event and not calling `element.focus()`.
This seems to have different behavior, as `element.focus()` is working with your repro:
https://stackblitz.com/edit/github-3auzsz-1iuaj8?file=src%2Fcomponents%2F__tests__%2FHelloWorld.spec.ts

I'm not sure if we should call the methods on the DOM element (if exists) instead of dispatching a DOM event?

---
Just an opinion on your test:
You are using the wrapper as your work element (which is actually the button):
```typescript
await wrapper.trigger('focus');
expect(document.activeElement).toBe(wrapper.element);
```

I would prefer to explicit use the button instead of `wrapper`. In that case it's clear the button should be the active element and will make the test still work when you need to add some `<div>` around or so.
```typescript
const button = wrapper.find('button');
await button.trigger('focus');
expect(document.activeElement).toBe(button.element);
```

**Comment by hzhoup** [comment] 2023-09-04 05:56
@freakzlike thaks, it helped me.

if I call `button.trigger('focus')` explicitly, then `document.activeElement`'s expect must be correct. There's no doubt about it, and I don't think there's any need for testing.

In my component, there may be certain factors that prevent it from being in focus. And the root component is a dynamic component, not necessarily a button.

I don't think explicitly calling `button.trigger('focus')` meets my test need.

**Comment by marina-mosti** [comment] 2023-10-19 08:21
> I want to test the wrapper focus state, in the [MDN Doc](https://developer.mozilla.org/en-US/docs/Web/API/Document/activeElement), i know `The activeElement read-only property of the Document interface returns the Element within the DOM that currently has focus.`. I think when i trigger `focus`, the `document.activeElement` will be return `button` DOM instead of `body`, like try that on the browser.
> 
> The preview link: https://stackblitz.com/edit/github-3auzsz-nb39qq?file=src%2Fcomponents%2F__tests__%2FHelloWorld.spec.ts,src%2FApp.vue
> 
> On the stackblitz side preview is always `iframe`, i open port new tab, in the browser console `document.activeElement` will be show: ![image](https://user-images.githubusercontent.com/109516832/264818822-3288eab8-6a52-4b6b-94d7-775c123b66e3.png)

Hey @hzhoup I was curious since I've had some pain testing focus events myself, so I took a hack at this.

If you open in a new tab and are very careful to not click anything, so using a keyboard shortcut for example to open the inspector you will notice that `document.activeElement` is actually the body as expected.

My guess is that either by mouse or keyboard you triggered the focus on the button before executing the `document.activeElement` call.

To be completely sure, I would add some thick border to the button on the `:focus` state so that you can be sure that you dont have it manually selected before executing the call. The default active element will usually be the body. In the stack page the active element is the iframe probably if you right click it to open the inspector.

What @cexbrayat suggested is correct though, and triggering the focus event on the wrapper should yield the whole wrapper as is happening in your test. The activeElement will not return the button unless you either:

1. Mock the user focusing the button by trigger('focus')
2. Programatically pre-focus the button for the user on the mounted hook for example

**Comment by cexbrayat** [comment] 2023-10-19 09:13
Thanks @marina-mosti for taking a look. I agree with you 👍 

Unless @freakzlike thinks #2180 is the way to go, I think this is expected behavior and we could close this.

**Comment by freakzlike** [comment] 2023-10-31 08:01
I'm completely fine if we don't merge #2180. Adds too much complexity in my opinion

**Comment by cexbrayat** [comment] 2023-10-31 08:25
👍 Let's close then

**Closed by cexbrayat** 2023-10-31 08:25 UTC
Labels: bug
