### ISSUE TITLE
Bug: clicking button type submit doesn't trigger submit event

### ISSUE THREAD

**Issue by ricardovanlaarhoven** [vuejs/test-utils#2346] opened 2024-02-19 07:50 UTC
**Describe the bug**
When creating a simple form, with a submit button. 
And you trigger a click on that button, the submit request is not triggered.
But when triggering a submit, it does work

**To Reproduce**
TestComponent.vue
```
<template>
  <form @submit.prevent="testFunction">
    <button type="submit">
      Submit
    </button>
    {{ isCalled }}
  </form>
</template>

<script setup>
import { ref } from "vue";

const isCalled = ref("Nope not called");
function testFunction () {
  isCalled.value = "Yes called";
}
</script>
```

The tests
```
  it("works", async () => {
    const wrapper = mount(TestComponent);
    await wrapper.find("form").trigger("submit");
    await flushPromises();
    expect(wrapper.html()).toContain("Yes");
  });


  it("doesnt work", async () => {
    const wrapper = mount(TestComponent);
    await wrapper.find("button").trigger("click");
    await flushPromises();
    expect(wrapper.html()).toContain("Yes");
  });
```

**Expected behavior**
Both test succeed

**Related information:**
https://github.com/vuejs/vue-test-utils/issues/2018#issuecomment-1915620471

**Comment by cexbrayat** [comment] 2024-02-19 08:00
You probably need to attach the component to the DOM, see this note in the docs https://test-utils.vuejs.org/guide/essentials/forms.html#Native-form-submission

**Comment by cexbrayat** [comment] 2024-02-19 08:02
Duplicate of https://github.com/vuejs/test-utils/issues/2318

**Closed by cexbrayat** 2024-02-19 08:02 UTC
Labels: bug
