### ISSUE TITLE
 Issue: tracking function calls in the context of watch block

### ISSUE THREAD

**Issue by Juliya2323** [vuejs/test-utils#2187] opened 2023-09-11 14:21 UTC
I'm facing an issue in my Vue.js component where I'm trying to spy on a function with vi.spyOn(). However, during the test, the spy doesn't seem to detect that the function is being called, even though I can see that the function is indeed being invoked in my component. Interestingly, if I add a console.log statement within the function, I can see the log output in the terminal, but the test still reports that the function isn't called.

The function I'm trying to spy on is also part of a watch block in my component. Could there be a connection between the watch block and the issue with the spy not working as expected? Are there any specific considerations or configurations I should be aware of when using spies in components with watch blocks in Vue.js tests?

**Comment by cexbrayat** [comment] 2023-09-11 15:31
Hi @Juliya2323 
It's hard to say without seeing any code, but I suspect this is normal behavior.

Can you provide us a small repro online using https://stackblitz.com/github/vuejs/create-vue-templates/tree/main/typescript-vitest?file=src%2Fcomponents%2F__tests__%2FHelloWorld.spec.ts ? 

It only takes a few minutes, and we'll be able to take a look

**Comment by Juliya2323** [comment] 2023-09-11 16:32
Here is the part of the code where this issue occurs.
Test:

describe('Search', () => {
  let wrapper: any


  beforeEach(async () => {
    setActivePinia(createPinia())
    wrapper = mount(GuestListPage, {
      global: {
        plugins: [untitled, createTestingPinia()],
      },
    })
  })


  // Test case: Search submitted with input
  it('search submitted with input', async () => {
    const searchSpy = vitest.spyOn(wrapper.vm, 'fetchGuests')
    const input = wrapper.find('[name="guest-list-search"]')
    await input.setValue('Test')
    await input.trigger('input')
    expect(searchSpy).toHaveBeenCalled() 
    expect(wrapper.vm.currentSearch).toBe('Test')
  })
})


Input element:
<div v-show="isSearching" class="min-w-[300px]">
            <u-input
              v-model="currentSearch"
              class="search-input"
              prepend-icon="search-sm"
              name="guest-list-search"
              size="sm"
              placeholder="Search"
              @blur="isSearching = false"
            ></u-input>
</div>


const currentSearch = ref('')


Watch:
watch(currentSearch, fetchGuests)


And finally function:
const fetchGuests = async () => {
  console.log('fetch guests was called')
  if (userStore.hotelId !== undefined && hotelsStore.data?.length) {
    try {
      isTableLoading.value = true
      const status =
        currentTab.value == 0
          ? 1
          : currentTab.value == 1
          ? 4
          : currentTab.value == 2
          ? 2
          : 0
      const params = {
        ///
      } as GuestRequest
      const response = await HotelService.getGuests(
        params,
        userStore.hotelId.toString(),
      )
      lastPage.value = response.meta.last_page
      if (currentPage.value > lastPage.value) {
        currentPage.value = lastPage.value
        updateQueryParam()
      } else {
        if (response.data.length) {
          guests.value = response.data
        } else {
          guests.value.length = 0
        }
      }
    } finally {
      isTableLoading.value = false
    }
  }
}

**Comment by cexbrayat** [comment] 2023-09-12 06:49
I think this is expected. I usually spy on `HotelService.getGuests` instead to make sure the watcher does call the service. See https://github.com/vuejs/test-utils/issues/775#issuecomment-883189164

But your code is really hard to read as it is incomplete and not formatted. If you want help from us, please take the time to build a small, simplified reproduction using https://stackblitz.com/github/vuejs/create-vue-templates/tree/main/typescript-vitest?file=src%2Fcomponents%2F__tests__%2FHelloWorld.spec.ts 

As I don't think this is an issue with VTU, I'll close the issue. Feel free to ping me with a repro and I'll re-open if necessary.

**Closed by cexbrayat** 2023-09-12 06:49 UTC

**Comment by Juliya2323** [comment] 2023-09-12 13:06
Hello, thanks for your respond.
Here is a simple reproduction by the link below.
https://stackblitz.com/edit/github-djqam6?file=src%2Fpages%2FGuestList.spec.ts

**Comment by cexbrayat** [comment] 2023-09-12 14:03
The code does not compile if I try to run `npm run test:unit` in the repro.

But I confirm what I was saying: spying on `wrapper.vm.fetchGuests` can't work because spying in JS does not work like that.

Let's take an example with an outside function `fnOutside` that calls an inside function `fnInside`:

```ts
it('should mock the function fnInside', () => {
    // this is the setup of your component
    const factory = () => {
      const fnInside = () => 10
      const fnOutside = () => fnInside()
      return { fnInside, fnOutside }
    }
   // this is the mount(Component)
    const obj = factory()
   // override fnInside
    obj.fnInside = vi.fn().mockReturnValue(1)
    expect(obj.fnInside()).toBe(1) // the override works and returns 1
    expect(obj.fnOutside()).toBe(1) // fails, returns 10, because it uses an internal reference to fnInside and not our override
})
```

In your example, the watcher calls `fetchGuests` directly, so spying on it will have no effect.
This is why you should spy on `hotelService.getGuests` instead.

I hope this helps
