### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Swoox** [vuejs/test-utils#2058] opened 2023-05-17 08:30 UTC
**Describe the bug**
If try to access a variable of an hook with a child component, the vue-tsc give an error. wrapper.vm does not have a stateForm property, because wrapper.vm is typed as ComponentPublicInstance.

**To Reproduce**
https://stackblitz.com/edit/vitest-dev-vitest-ztd6bn

**Expected behavior**
No error.

**Related information:**
See https://github.com/vuejs/test-utils/issues/972
Tested with https://github.com/vuejs/test-utils/pull/2026

**Workaround**
```
const childComp = wrapper.findComponent(ChildComp);
const childWrapper = mount(childComp);
expect(childWrapper.vm.stateForm.length).toBe(undefined);
```

**Comment by cexbrayat** [comment] 2023-05-17 08:36
Yeah, as you mentioned this is related to #972 , and we can't fix it in VTU, it has to be fixed in either Vue itself or Volar.

As a workaround, you can expose `stateForm` or explicitly cast `wrapper.vm` in your test.

Closing as duplicate of #972

**Closed by cexbrayat** 2023-05-17 08:36 UTC
Labels: bug

**Comment by Swoox** [comment] 2023-05-17 08:56
I actually tested https://github.com/vuejs/test-utils/issues/972 with https://github.com/vuejs/test-utils/pull/2026 and seems that 2026 fixes 972.
Check https://stackblitz.com/edit/vitest-dev-vitest-1rkt44?file=package.json

**Comment by cexbrayat** [comment] 2023-05-17 09:11
`time` being undefined sounds correct no? But `times` should be `2`

But if that compiles correctly then this is a regression in the types of `wrapper.vm`  in the alpha release: `wrapper.vm.type` should not compile

**Comment by Swoox** [comment] 2023-05-17 09:24
Ofc time is undefined..
`expect(wrapper.vm.times).toBe(4);`
My bad.
