### ISSUE TITLE
Bug: Documenation is not complete: how to define a parent component in #mount?

### ISSUE THREAD

**Issue by dima4p** [vuejs/test-utils#1778] opened 2022-09-19 17:01 UTC
**Describe the bug**

In the previous version for Vue 2 the method `mount` had the option `parentComponent`. Now it is gone, 

But in the documentation it is not described how to define a parent component in `mount`.

Please, supply the information. So that I can use `this.$parent` in my component and the specs do not fail.

**Comment by xanf** [comment] 2022-10-02 18:54
@dima4p There is no way to define `parentComponent` in new version of @vue/test-utils because... it is not needed. It could be easily achieved manually.

Let's assume you're having a component `NeedsParent` which you want to test, which needs some specific parent. You could easily do:

```js
const Parent = {
  components: { NeedsParent },
  // ...some options required here...
  template: '<needs-parent />'
}

const wrapper = mount(Parent)
```

You might need to write some minor code in `Parent`, for example if you want to be able to manipulte props passed to `<need-parent />` via `setProps` API, however, this, actually, was the case in old @vue/test-utils also :)

I'm closing this one as working as intended

**Closed by xanf** 2022-10-02 18:54 UTC
Labels: bug
