### ISSUE TITLE
Bug: Cannot acess global plugin in test file (wrapper.vm.$plugin)

### ISSUE THREAD

**Issue by ElVisPL** [vuejs/test-utils#2298] opened 2024-01-10 11:17 UTC
**Describe the bug**

I'm migrating vue2 to vue3 (test utils too)
In vue2 if I had global plugin that was installed with `createLocalVue` then it was accessible under `wrapper.vm` (e.g `wrapper.vm.$logger`), in vue3 if i pass plugin to `global.plugins` then it is passed correctly to tested component, but in the test itself I don't have access to it so e.g I can't mock it

It works though for external provider plugins like vuetify (`wrapper.vm.$vuetify` is there)

**To Reproduce**

https://stackblitz.com/edit/github-guxdre-g64fcl?file=src%2Fcomponents%2F__tests__%2FHelloWorld.spec.ts

In test file see console.log

**Expected behavior**

Global plugin is accessible e.g `wrapper.vm.$logger`

**Comment by cexbrayat** [comment] 2024-01-11 10:38
Hi @ElVisPL 
Thanks for the repro. 

Interesting, because we have a similar test case in this repo https://github.com/vuejs/test-utils/blob/main/tests/config.spec.ts 
So I would have expected this to work as well.

Do you think you could look into it and open a PR? We would gladly review it and merge it. The test file I mentioned is a good place to try to add your repro and see if you still reproduce the issue.

**Comment by taku-y-9308** [comment] 2024-03-29 05:38
@cexbrayat 
Has this issue been fixed by my pr?
https://github.com/vuejs/test-utils/pull/2386

**Comment by cexbrayat** [comment] 2024-03-29 15:47
@taku-y-9308 Maybe it does, I'm not sure. We'll check when the new version is released 👍

**Comment by cexbrayat** [comment] 2024-05-07 06:54
I think @taku-y-9308 did fix the issue: if I update to v2.4.6 in @ElVisPL 's stacklitz repro, the `$logger` is defined.

Let's close the issue, and thanks @taku-y-9308 for solving this.

**Closed by cexbrayat** 2024-05-07 06:54 UTC
Labels: bug
