### ISSUE TITLE
Bug: typing error using Vue 3.2.45, VTU 2.2.3 and TypeScript 4.9.3

### ISSUE THREAD

**Issue by felixzapata** [vuejs/test-utils#1873] opened 2022-11-17 08:13 UTC
**Describe the bug**

 There are typing errors related to TypeScript after running a typing check over test files.

The error shows traces to the `node_modules/@vue/test-utils/dist/mount.d.ts` file.

**To Reproduce**

https://stackblitz.com/edit/vitejs-vite-msu15a

`npm run type-check`

**Expected behavior**
No typing error as the same result as previous versions. The last one we were using without typing errors was `4.8.4`

**Related information:**
```
System:
    OS: macOS 11.6.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 140.00 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
    Yarn: 3.2.3 - ~/.nvm/versions/node/v18.7.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v18.7.0/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Chrome Canary: 110.0.5423.0
    Firefox: 106.0.5
    Safari: 15.5
    Safari Technology Preview: 15.4
  npmPackages:
    @intlify/core-base: 9.2.2 => 9.2.2 
    @intlify/eslint-plugin-vue-i18n: ^2.0.0 => 2.0.0 
    @intlify/unplugin-vue-i18n: 0.8.0 => 0.8.0 
    @vitejs/plugin-vue: 3.2.0 => 3.2.0 
    @vue/eslint-config-typescript: 11.0.2 => 11.0.2 
    @vue/test-utils: 2.2.3 => 2.2.3 
    @vue/tsconfig: 0.1.3 => 0.1.3 
    vite: 3.2.4 => 3.2.4 
    vitest: 0.25.2 => 0.25.2 
    vue: 3.2.45 => 3.2.45 
    vue-i18n: 9.2.2 => 9.2.2 
    vue-loader: 17.0.1 => 17.0.1 
    vue-router: 4.1.6 => 4.1.6 
    vue-tsc: 1.0.9 => 1.0.9 
```

**Additional context**
N/A

**Comment by cexbrayat** [comment] 2022-11-17 08:20
Hi @felixzapata 

👍 I'm going to close this one as a duplicate of #1872

**Closed** 2022-11-17 08:21 UTC
Labels: bug

**Comment by felixzapata** [comment] 2022-11-17 08:23
ops sorry, my mistake. I did not realize that issue.
