### ISSUE TITLE
Not able to mock $root

### ISSUE THREAD

**Issue by hilkisahil** [vuejs/test-utils#1877] opened 2022-11-18 14:57 UTC
I'm using vue 3 and vue-test-utils v2 . I have a component which uses $root to listen events. When I try to test this component it fails by throwing error 'this.$root.$on'  is not a function.
I have even tried using mounting options 'parentComponent' but not working.

```
const Parent = {
  data() {
    return {
      $on: jest.fn(),
    }
  }
}
const wrapper = shallowMount(TestComponent, {
  parentComponent: Parent
})
```

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/100563716/202732830-145aab9f-af27-4fdb-a5a9-9e099fbdcc00.png)

**Comment by cexbrayat** [comment] 2022-11-18 16:09
Hi @hilkisahil 

If you are using vue v3.2.45, then yes there is a change in vue core that we have to work around in VTU
We already have the fix, and we are going to release it soon

Closing as duplicate of #1869

**Closed by cexbrayat** 2022-11-18 16:09 UTC
