### ISSUE TITLE
Bug: expose props can not access in test case.

### ISSUE THREAD

**Issue by jason-chang** [vuejs/test-utils#2116] opened 2023-07-03 02:08 UTC
**Describe the bug**
`defineExpose` can works fine in the browser, but does not work in the test case.
Got error like ⬇️
![image](https://github.com/vuejs/test-utils/assets/4367687/2a01198a-ffc7-4bf5-92bb-426dec7841d1)

**To Reproduce**
To reproduce this problem I created a demo and put it in the `CodeSandbox`.

The link is here ⬇️

[https://codesandbox.io/p/github/jason-chang/test-utils-bug/main](https://codesandbox.io/p/github/jason-chang/test-utils-bug/main?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522cljm6iboc000b3t6mbgq6k9hd%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522cljm6l64200rk3t6mj2lxjc6g%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B55.79907603384709%252C44.20092396615291%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cljm6iboc000b3t6mbgq6k9hd%2522%253A%257B%2522id%2522%253A%2522cljm6iboc000b3t6mbgq6k9hd%2522%252C%2522activeTabId%2522%253A%2522cljm7uh2r01l03t6msmmziw70%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cljm6iboc000a3t6mi44x6xf9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fcomponents%252FCase.vue%2522%252C%2522id%2522%253A%2522cljm7uh2r01l03t6msmmziw70%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fcomponents%252Ftests%252Fcase.test.tsx%2522%252C%2522id%2522%253A%2522cljm7whqo02433t6mv2uvhtwu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522cljm6l64200rk3t6mj2lxjc6g%2522%253A%257B%2522id%2522%253A%2522cljm6l64200rk3t6mj2lxjc6g%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cljm6iboc000c3t6mozc659nt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%257D%252C%257B%2522id%2522%253A%2522cljm6jf9i00ag3t6mabx9by3g%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522test%2522%257D%252C%257B%2522id%2522%253A%2522cljm6jxg700gj3t6mngwznps0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522cljm6yvmt00yt3t6m78k2dbn7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522dev%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cljm6jf9i00ag3t6mabx9by3g%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Components in `src/components/Case.vue`
For test cases, see `src/components/tests/case.test.tsx`
The browse test code is in `src/App.vue`

**Expected behavior**

You want defineExpose exported projects to be properly accessible in both browser and test case.

**Related information:**

**Additional context**

**Comment by cexbrayat** [comment] 2023-07-03 14:03
Hi @jason-chang 

Thank you for the repro.
This is interesting and probably need to be fixed. We expose everything automatically on `wrapper.vm`, even without `defineExpose`, to make tests easier. But maybe we need some special handling for the aliases

If you're interested in contributing, there are tests in `expose.spec.ts`. You can try to add a test with an alias if there is none. The code to fix will be in `vueWrapper.ts`, around https://github.com/vuejs/test-utils/blob/ba53cfb949b998e77ee6af2e4e4a3ea981b012e1/src/vueWrapper.ts#L23

**Comment by erikkkwu** [comment] 2023-07-05 09:31
I'm not sure if implementing it this way in createVMProxy is a good approach, because it depends on the unref method
<img width="847" alt="image" src="https://github.com/vuejs/test-utils/assets/40494306/cfcad10e-8330-493b-8614-5c7c595cefc5">

**Comment by cexbrayat** [comment] 2023-07-05 18:27
I'm pretty sure it's a test-utils problem. You can start by adding a unit test expose.spec.ts and see if it reproduces the problem. If it's too hard to fix no worries, someone from the team will take a look when we get some time 😉. Thanks!

**Comment by jason-chang** [comment] 2023-07-07 11:45
@cexbrayat ok👌

**Comment by jason-chang** [comment] 2023-07-08 12:34
@cexbrayat @erikkkwu Thanks your tips, I tried to create a pull request to fix & test this bug. #2125 
Please review and decide whether to merge or not.

**Closed** 2023-07-20 20:49 UTC
Labels: bug
